jobs:   
        build:
                working_directory: /webapp
                docker:
                        - image: node
                steps:
                        - run: npm install
                        - run: npm test
                       
deployment: 
        commands:
                - deployment.sh
